# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6XkR46jb_1cH0du7lS_2Nga5D3zrgCr
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

df = pd.read_csv('/content/tehranhouses.csv')
df.head()

df.tail()

df.info()

df.sample(4)

df['Warehouse'] = df['Warehouse'].map({'False':0 , 'True':1})
df['Elevator'] = df['Elevator'].map({'False':0 , 'True':1})
df['Parking'] = df['Parking'].map({'False':0 , 'True':1})

df.head()

A=df['Address']

A.head()

df.drop('Address' ,axis=1 ,inplace =True)

df.head()

rev_null=['Area','Room','Parking','Warehouse','Elevator','Price','Price(USD)']
df[rev_null]= df[rev_null].replace({
np.nan:df['Area'].mode(),
np.nan:df['Room'].mode(),
np.nan:df['Parking'].mode(),
np.nan:df['Warehouse'].mode(),
np.nan:df['Elevator'].mode(),
np.nan:df['Price'].mean(),
np.nan:df['Price(USD)'].mean()})

df.isnull().sum()

X = df.drop(columns=['Area','Room','Warehouse','Elevator','Parking']).values
y = df['Price'].values

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

print(type(X_train))

X_train = pd.DataFrame(X_train)
X_train = X_train.apply(pd.to_numeric,errors='coerce')

sns.scatterplot(dataset, x= 'Area', y='Price', hue='Room' )
plt.xlabel=['Price']
plt.ylabel=['Area']

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy',random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))